### ISSUE TITLE
`onSuggestionSelected` method is not able to called with flutter 3.7 version 

### ISSUE THREAD

**Issue by sumitsharansatsangi** [AbdulRahmanAlHamali/flutter_typeahead#446]
Up to Flutter 3.3.10 version `onSuggestionSelected` method was working correctly , But after upgrading to Flutter 3.7 version, it won't be called.

**Comment by Ahmadre** [comment]
This has not only to do with the Flutter version.

It is very buggy at all....

I am just figuering out why...

**Comment by Ahmadre** [comment]
@AbdulRahmanAlHamali

**Comment by yom-ko** [comment]
Same problem. Looks like Focus behaviour for text fields has changed significantly in the latest Flutter version (3.7.0).

**Comment by jobypthomas** [comment]
@AbdulRahmanAlHamali same issue here as well

**Comment by SunnatilloShavkatov** [comment]
hideSuggestionsOnKeyboardHide: false,  

It worked for me.

**Comment by jobypthomas** [comment]
Someone called "Sunnatillo Shavkatov" suggested to use `hideSuggestionsOnKeyboardHide: false,` and it worked for me.

**Comment by felipecastrosales** [comment]
@jobypthomas not works here. :(

**Comment by hisham-89** [comment]
It is solved
wrap it in 
                SingleChildScrollView(
                  scrollDirection: Axis.vertical,
              child: TypeAheadFormField())

https://stackoverflow.com/questions/74888370/scrollable-of-was-called-with-a-context-that-does-not-contain-a-scrollable-wid

**Comment by hhandika** [comment]
> Someone called "Sunnatillo Shavkatov" suggested to use `hideSuggestionsOnKeyboardHide: false,` and it worked for me.

This solution works for iOS and desktop OS. It still does not work on Android.

**Comment by alphamikle** [comment]
I see the same problem on MacOS and the Web. I will attach a video (where I'm trying to drag the scrollbar and clicking on it) that shows that the problem is not really that the `onTap` callback of `InkWell` does not work, it looks as if something is absorbing any click in the hint area, and any click in the hint area is triggered as if it were made outside that area.

https://user-images.githubusercontent.com/29115406/215214202-d126f716-896b-4ea1-84fb-e4c2581ef2a2.mp4

**Comment by BenjiFarquhar** [comment]
> > Someone called "Sunnatillo Shavkatov" suggested to use `hideSuggestionsOnKeyboardHide: false,` and it worked for me.
> 
> This solution works on iOS and desktop OS. It still does not work on Android.

For anyone here with this issue but on Flutter 3.3.10, I was facing this issue if I used a FocusNode (with no FocusNode it always worked). With the quoted solution, it works for me on iOS, Web, and Android with a FocusNode.

**Comment by sjmcdowall** [comment]
It appears we have a new approach on how to get this working.  Also try the new build I just published for 3.7.0 (although no idea if that fixes this issue but does fix another imcompatibility)

**Comment by alphamikle** [comment]
Hey all! I've just tried the latest version `4.3.1`, and it didn't help with a discussed problem, at least on MacOS and Desktop Web. I researched the source code and found a pretty shitty but non-compromised working solution. You need to add a little delay to the first fragment of the code and reduce the delay of the second fragment:

```dart
// ...
this._focusNodeListener = () {
      if (_effectiveFocusNode!.hasFocus) {
        this._suggestionsBox!.open();
      } else if (!_areSuggestionsFocused) {
        if (widget.hideSuggestionsOnKeyboardHide) {
          Future<void>.delayed(const Duration(milliseconds: 110), () { // <- THAT ONE
            if (mounted) {
              this._suggestionsBox?.close();
            }
          });
        }
      }

      widget.onSuggestionsBoxToggle?.call(this._suggestionsBox!.isOpened);
    };
// ...
Future<bool> _waitChangeMetrics() async {
    if (widgetMounted) {
      // initial viewInsets which are before the keyboard is toggled
      EdgeInsets initial = MediaQuery.of(context).viewInsets;
      // initial MediaQuery for orientation change
      MediaQuery? initialRootMediaQuery = _findRootMediaQuery();

      int timer = 0;
      // viewInsets or MediaQuery have changed once keyboard has toggled or orientation has changed
      while (widgetMounted && timer < waitMetricsTimeoutMillis) {
        // TODO: reduce delay if showDialog ever exposes detection of animation end
        await Future<void>.delayed(const Duration(milliseconds: 100)); // <- AND THAT TOO
        timer += 100; // <- AND THAT FINALLY

        if (widgetMounted && (MediaQuery.of(context).viewInsets != initial || _findRootMediaQuery() != initialRootMediaQuery)) {
          return true;
        }
      }
    }

    return false;
  }
```
If we only pass a `hideSuggestionsOnKeyboardHide: false`, then the suggestions box will always be visible until we select some of the suggestion elements (on MacOS and Desktop Web, at least). But it can be impossible in some cases (for example - you have no suggestion elements).

---

Video example with only passing an argument `hideSuggestionsOnKeyboardHide: false`

https://user-images.githubusercontent.com/29115406/215286589-72b5f551-98fa-44c8-b087-e9bc8f72beed.mp4

Video example without passing that argument, but with added delay

https://user-images.githubusercontent.com/29115406/215286717-8de245ed-1040-42d0-8efc-0c4791e5bf5b.mp4

**Comment by BrayFlex** [comment]
@alphamikle I tried your solution on Windows Desktop Web in debug and didn't have success, I tried giving more room between the timers but I still couldn't get it to work for me so I ultimately went with defeating keyboard which works on the platform I am on, will test more later.

**Comment by sayantan-poddar06** [comment]
`ignoreAccessibleNavigation: true` -  this is solution,voila!!!
